local MOBILE_REQ_BASE = 30000	 
local GAME_REQ_BASE = 50000
local target = {
	SEND_PULSE		=(MOBILE_REQ_BASE + 1);-- 心跳
	CHECK_VERSION	=(MOBILE_REQ_BASE + 2);-- 此请求号必须固定值,应对版本升级

	GET_SERVERS		=(MOBILE_REQ_BASE + 10);-- 此请求号必须固定,应对版本升级
	GET_AREAS		=(MOBILE_REQ_BASE + 11);-- 获取游戏区 
	GET_ROOMS		=(MOBILE_REQ_BASE + 12);-- 获取房间
	GET_DXXWROOM    =(MOBILE_REQ_BASE + 13);-- 获取断线续玩房间信息=(不等回应)
	GET_ROOMUSERS		=(MOBILE_REQ_BASE + 14);-- 获取指定房间在线人数=(不等回应)
	GET_GAMELEVEL		=(MOBILE_REQ_BASE + 15);-- 获取游戏等级=(不等回应)
	GET_ASSISTSVR		=(MOBILE_REQ_BASE + 16);-- 获取AssistSvr

	LOGON_USER  		=(MOBILE_REQ_BASE + 100);-- 用户登陆
	LOGOFF_USER			=(MOBILE_REQ_BASE + 101);-- 用户注销

	GET_RNDKEY			=(MOBILE_REQ_BASE + 120);-- 获取随机密码
	GET_TEMPWEBSIGN		=(MOBILE_REQ_BASE + 121);-- 获取临时票据
	GET_WEBSIGN			=(MOBILE_REQ_BASE + 122);-- 获取网页票据

	REG_USER  			=(MOBILE_REQ_BASE + 140);-- 注册新用户
	RESET_PASSWORD  		=(MOBILE_REQ_BASE + 141);-- 重设密码
	QUICK_REG  			=(MOBILE_REQ_BASE + 142);-- 一键注册
	REG_NICKINFO  		=(MOBILE_REQ_BASE + 143);-- 修改昵称性别
	MODIFY_USERNAME		=(MOBILE_REQ_BASE + 144);-- 移动端修改用户名

	QUERY_USERID  		=(MOBILE_REQ_BASE + 160);-- 查询用户名
	QUERY_SAFE_DEPOSIT	=(MOBILE_REQ_BASE + 161);-- 查询保险箱
	QUERY_USER_GAMEINFO	=(MOBILE_REQ_BASE + 162);-- 查询游戏信息
	QUERY_SALARY_DEPOSIT	=(MOBILE_REQ_BASE + 163);-- 查询游戏工资
	QUERY_BACKDEPOSIT		=(MOBILE_REQ_BASE + 164);-- 查询游戏后备箱
	QUERY_MEMBER			=(MOBILE_REQ_BASE + 165);-- 查询会员状态

	MOVE_SAFE_DEPOSIT		=(MOBILE_REQ_BASE + 180);-- 划保险箱银子到游戏
	TRANSFER_DEPOSIT		=(MOBILE_REQ_BASE + 181);-- 游戏银子存入保险箱
	TAKE_SALARY_DEPOSIT		=(MOBILE_REQ_BASE + 182);-- 领取游戏工资
	TAKE_GIFT_DEPOSIT		=(MOBILE_REQ_BASE + 183);-- 领取赠送银子
	TAKE_BACKDEPOSIT		=(MOBILE_REQ_BASE + 184);-- 划后备箱银子到游戏
	SAVE_BACKDEPOSIT		=(MOBILE_REQ_BASE + 185);-- 游戏银子存入后备箱
	MOVEDEPOSIT_SAFETOBACK	=(MOBILE_REQ_BASE + 186);-- 保险箱转入后备箱
	MOVEDEPOSIT_BACKTOSAFE	=(MOBILE_REQ_BASE + 187);-- 后备箱转入保险箱
	MOVEDEPOSIT_BACKTOBACK	=(MOBILE_REQ_BASE + 188);-- 多个游戏后备箱之间互转
	TAKE_SALARYDEPOSIT_TOBACK =(MOBILE_REQ_BASE + 189);-- 领取游戏工资,并送入后备箱

	QUERY_WEALTH			=(MOBILE_REQ_BASE + 190);-- 查询通宝
	EXCHANGE_WEALTH			=(MOBILE_REQ_BASE + 191);-- 通宝兑换成银子，存入保险箱=(是否能冲入游戏)

	HTTP_GET				=(MOBILE_REQ_BASE + 200);-- 移动端访问Http Get方式请求代理

	UPDATE_SPECIFY_USERINFO =(MOBILE_REQ_BASE + 210);-- 根据flag更新用户指定信息，有网站更换服装、使用会员道具后触发

	ENTER_ROOM  			=(MOBILE_REQ_BASE + 500);-- 进房间
	LEAVE_ROOM				=(MOBILE_REQ_BASE + 501);-- 离开房间
	GET_NEWTABLE			=(MOBILE_REQ_BASE + 520);-- 请求一个座位
	ASK_ENTERGAME   	 	=(MOBILE_REQ_BASE + 521);-- 要求加入游戏
	REFRESH_MEMBER			=(MOBILE_REQ_BASE + 522);-- 刷新会员
	GET_GAMEVERISON			=(MOBILE_REQ_BASE + 523);-- 获取游戏版本信息

	GET_FINISHED			=(MOBILE_REQ_BASE + 530);-- 结束
----------------------------------------------------------
-- 系统通知
--	GET_FINISHED			=(GAME_REQ_BASE + 165);		-- 结束
	ADMINMSG_TO_ROOM   	 	=(GAME_REQ_BASE + 803);		-- 发送房间网管消息
	DEPOSIT_NOTENOUGH	  	=(GAME_REQ_BASE + 10005);		-- 银子不够
	EXPERIENCE_NOTENOUGH	=(GAME_REQ_BASE + 10006);		-- 经验值不够
	LEVEL_NOTENOUGH		  	=(GAME_REQ_BASE + 10008);		-- 级别不够
	ROOM_FULL			    =(GAME_REQ_BASE + 10009);		-- 房间满了
	NO_CHAIRS				=(GAME_REQ_BASE + 10010);		-- 位置满了
	IP_FORBIDDEN			=(GAME_REQ_BASE + 10012);		-- IP不符合要求
	CONTINUE_REG			=(GAME_REQ_BASE + 10013);		-- 同一台机器不能连续注册
	NORIGHTS_TO_ENTER	  	=(GAME_REQ_BASE + 10014);		-- 无权进入该房间
	NO_THIS_FUNCTION 	  	=(GAME_REQ_BASE + 10017);		-- 该功能暂不支持
	PLAYING_GAME      	  	=(GAME_REQ_BASE + 10018);		-- 游戏正在玩
	SYSTEM_LOCKED      		=(GAME_REQ_BASE + 10019);		-- 系统维护中
	FORBID_WORD       	  	=(GAME_REQ_BASE + 10020);		-- 禁止的词（无法注册）
	SIMPLE_PASSWORD    		=(GAME_REQ_BASE + 10021);		-- 密码太简单
	TOKENID_MISMATCH    	=(GAME_REQ_BASE + 10023);		-- token不匹配
	HARDID_MISMATCH     	=(GAME_REQ_BASE + 10027);		-- 硬件认证失败
	CONTINUE_PWDWRONG	  	=(GAME_REQ_BASE + 10029);	    -- 同一台机器不能连续密码错误
	DEPOSIT_OVERFLOW  	  	=(GAME_REQ_BASE + 10030);	    -- 银子太多了
	ERROR_INFOMATION     	=(GAME_REQ_BASE + 10031);	    -- 返回错误信息
	INVALID_WORD         	=(GAME_REQ_BASE + 10032);	    -- 无效的名字
	ROOM_FORBID_IP       	=(GAME_REQ_BASE + 10033);	    -- 用户所在IP被禁止进入房间
	NO_PERMISSION        	=(GAME_REQ_BASE + 10035);	    -- 没有许可
	SCORE_NOTENOUGH		  	=(GAME_REQ_BASE + 10036);		-- 分数不够
	SCORE_OVERFLOW   	  	=(GAME_REQ_BASE + 10037);	    -- 分数太多了
	PWDLEN_INVALID		    =(GAME_REQ_BASE + 10038);     	-- 密码长度无效
	NEED_LOGON           	=(GAME_REQ_BASE + 10039);	    -- 用户需要登陆先
	ROOM_NOT_EXIST       	=(GAME_REQ_BASE + 10040);	    -- 房间不存在
	ROOM_NEED_DXXW       	=(GAME_REQ_BASE + 10041);     	-- 正在另一个房间里玩
	NODEPOSIT_GAME       	=(GAME_REQ_BASE + 10042);     	-- 该游戏不能存放银子
	NAMELEN_INVALID      	=(GAME_REQ_BASE + 10043);     	-- 用户名长度不合适
	OLD_HALLBUILDNO      	=(GAME_REQ_BASE + 10044);     	-- 大厅buildno旧了，无法进入roomsvr
	FORBID_NODIANXINIP   	=(GAME_REQ_BASE + 10045);	    -- 非电信用户无法进入 。
	FORBID_ENTERROOM     	=(GAME_REQ_BASE + 10046);
	FORBID_SAMEHARDID  		=(GAME_REQ_BASE + 10047);		-- 禁止同网卡同房
	FORBID_SAMEIPINROOM  	=(GAME_REQ_BASE + 10048);		-- 禁止同IP同房
	ROOM_CLOSED          	=(GAME_REQ_BASE + 10050);		-- 房间已关闭
	ROOM_DIANXIN         	=(GAME_REQ_BASE + 10051);		-- 电信专属房间 
	SCREEN_NOTENOUGH     	=(GAME_REQ_BASE + 10052);		-- 分辩率不够
	WINSYSTEM_NOTENOUGH  	=(GAME_REQ_BASE + 10053);		-- 操作系统不够
	WINSYSTEM_NOTSUPPORT 	=(GAME_REQ_BASE + 10054);		-- 操作系统不支持
	RNDKEY_WRONG	        =(GAME_REQ_BASE + 10055);	    -- 验证码不正确
	FORBID_PROXY         	=(GAME_REQ_BASE + 10056);	    -- 禁止代理服务 。
	OLD_EXEMINORVER      	=(GAME_REQ_BASE + 10057);    	-- roomexe旧了，无法进入roomsvr
	RNDKEY_TOOMUCHWRONG  	=(GAME_REQ_BASE + 10058);	    -- 验证码不正确次数太多
	INVALID_IDCARD       	=(GAME_REQ_BASE + 10060);		-- 身份证号格式不对 
	INVALID_TRUENAME     	=(GAME_REQ_BASE + 10061);		-- 真实姓名格式不对
	OLD_EXEMAJORVER      	=(GAME_REQ_BASE + 10065);
	FORBID_PROXYIP       	=(GAME_REQ_BASE + 10066);
	PLAYSCORE_NOTENOUGH  	=(GAME_REQ_BASE + 10067);  
	PLAYSCORE_OVERFLOW   	=(GAME_REQ_BASE + 10068);
	BOUT_NOTENOUGH       	=(GAME_REQ_BASE + 10070);
	TIMECOST_NOTENOUGH   	=(GAME_REQ_BASE + 10071);
	NEED_ENTERGAME       	=(GAME_REQ_BASE + 10073);
	ROOM_NEEDSIGNUP      	=(GAME_REQ_BASE + 10074);
	MATCHSCORE_NOTENOUGH 	=(GAME_REQ_BASE + 10075);
	OLD_EXEBUILDNO   		=(GAME_REQ_BASE + 10077);	   -- 游戏buildno旧了
	ROOM_NOT_OPENED      	=(GAME_REQ_BASE + 10078);
	LOGON_NEED_ACTIVATE  	=(GAME_REQ_BASE + 10081);
	FORBID_VIRTUAL       	=(GAME_REQ_BASE + 10083);  
	NO_MOBILEUSER	      	=(GAME_REQ_BASE + 10085);  
	INPUTLIMIT_DAILY		=(GAME_REQ_BASE + 10086);  
	SERVICE_BUSY		    =(GAME_REQ_BASE + 10087);
	LOGON_SUCCEEDED		  	=(GAME_REQ_BASE + 10090);		-- 登录成功
	KEEPDEPOSIT_LIMIT      	=(GAME_REQ_BASE + 10092);
	NOT_QUICKREGUSER		=(GAME_REQ_BASE + 10093);		-- 非快速注册用户
	NEW_EXEMAJORVER			=(GAME_REQ_BASE + 10096);		-- 版本过高 主
	NEW_EXEMINORVER			=(GAME_REQ_BASE + 10097);		-- 版本过高 次
	NEW_EXEBUILDNO			=(GAME_REQ_BASE + 10098);		-- 版本过高 日期
	NEW_HALLBUILDNO			=(GAME_REQ_BASE + 10105);		-- 版本过高 大厅版本号
	USER_LOCKED			    =(GAME_REQ_BASE + 10100);		-- 用户已被锁定
	USER_FORBIDDEN		    =(GAME_REQ_BASE + 10101);		-- 用户已被禁用
	FORBID_EXPIRATION 	  	=(GAME_REQ_BASE + 10102);		-- 用户已被禁用但已经可以到期解禁
	FORBID_UNEXPIRATION 	=(GAME_REQ_BASE + 10103);		-- 用户已被禁用,还未到期解禁
	ENTER_CLOAKINGROOM_OK	=(GAME_REQ_BASE + 19996);		-- 进入隐身房间成功
	ENTER_ROOM_OK		    =(GAME_REQ_BASE + 20000);		-- 进入房间成功

	PLAYER_ENTERED			=(GAME_REQ_BASE + 30000);		-- 玩家进入房间
	PLAYER_SEATED			=(GAME_REQ_BASE + 30001);		-- 玩家就座
	PLAYER_STARTED			=(GAME_REQ_BASE + 30003);		-- 玩家开始玩游戏
	KICKEDOFF_LOGONAGAIN	=(GAME_REQ_BASE + 30103);		-- 玩家被踢出
	KICKEDOFF_BYADMIN	  	=(GAME_REQ_BASE + 30104);		-- 玩家被踢出
	USER_EVIDENCE        	=(GAME_REQ_BASE + 30605);		-- 帐号核实凭据
	GET_SERVERS_OK	      	=(GAME_REQ_BASE + 30691);		-- 获取服务器成功
	GET_ROOMUSERS_OK     	=(GAME_REQ_BASE + 30702);		-- 房间在线人数通知
	GET_GAMELEVEL_OK     	=(GAME_REQ_BASE + 30703);		-- 游戏级别通知
	GET_DXXWROOM_OK      	=(GAME_REQ_BASE + 30704);		-- 断线房间信息通知
	GET_WEBSIGN_OK		 	=(GAME_REQ_BASE + 30709);		--  
	SYSTEM_MESSAGE		    =(GAME_REQ_BASE + 30800);		-- 系统通知
	KICKOFF_ROOM_PLAYER   	=(GAME_REQ_BASE + 839);	    	-- 所在服务器上的某个房间剔除某个玩家
	MATCH_NOTREADY      	=(GAME_REQ_BASE + 30900);		-- 比赛系统通知

	GET_SERVERS_OK		=(GAME_REQ_BASE + 30691);-- 获取服务器成功
	GET_GROUPUSERS_OK	=(GAME_REQ_BASE + 30699);-- 在线人数
	GET_GAMEUSERS_OK	=(GAME_REQ_BASE + 30701);-- 游戏在线人数通知
    GET_ROOMUSERS_OK	=(GAME_REQ_BASE + 30702);-- 房间在线人数通知  
    GET_GAMELEVEL_OK	=(GAME_REQ_BASE + 30703);-- 游戏级别通知
    GET_DXXWROOM_OK		=(GAME_REQ_BASE + 30704);-- 断线房间信息通知
	GET_FRIENDSONLINE_OK=(GAME_REQ_BASE + 30705);-- 在线好友通知
    GET_GAMEWWW_OK      =(GAME_REQ_BASE + 30706);
    GET_SERVICESTATUS_OK=(GAME_REQ_BASE + 30707);
    GET_ICONFILE_OK		=(GAME_REQ_BASE + 30708);
    GET_WEBSIGN_OK		=(GAME_REQ_BASE + 30709);
	BASE_DATA			=(GAME_REQ_BASE + 30710);-- 系统信息刷新通知
    GET_SERVICESTATUSEX_OK =(GAME_REQ_BASE + 30711);-- 
	CLIENT_FORBID		=(GAME_REQ_BASE + 30720);-- 客户端禁用
	SYSTEM_MESSAGE		=(GAME_REQ_BASE + 30800);-- 系统通知
    MATCH_NOTREADY      =(GAME_REQ_BASE + 30900);-- 比赛系统通知
	PUSH_NOTIFY			=(GAME_REQ_BASE + 31000);-- 推送通知到客户端

--系统内部通知请求
	NTF_PLAYERLOGON		=(GAME_REQ_BASE + 31001);-- 玩家登录
	NTF_PLAYERLOGOFF	=(GAME_REQ_BASE + 31002);-- 玩家注销
	RSS_PLAYERLOGONOFF	=(GAME_REQ_BASE + 31003);-- 订阅玩家登录、注销通知
	QUERY_PLAYERLOGON	=(GAME_REQ_BASE + 31004);-- 查询玩家登录信息
}

target.Flags = {
USER_TYPE_HANDPHONE =   	  0x00000800;	--手机用户

SERVER_OPT_SUPPORTMOBILE =    0x00000800;      --手机可见
AREA_OPT_SUPPORTMOBILE =      0x00000800;      --手机可见
ROOM_OPT_SUPPORTMOBILE =      0x00000800;      --手机可见
ROOM_CFG_SUPPORTMOBILE =      0x00000800;  	--支持手机玩


FLAG_GETAREAS_INCLUDE_HIDE =    0x00000001;  --获取area时包括隐藏的area,link
FLAG_LOGON_HANDPHONE =    	0x00000800;  	--手机进入 
FLAG_LOGON_INTER =	    	0x00001000;		--多开模拟器
FLAG_GETAREAS_MOBILE =  	0x00000800;  	--手机获取
FLAG_GETROOMS_MOBILE =    0x00000800;      --手机获取
FLAG_GETSERVERS_MOBILE =  0x00000800;  	--手机获取
FLAG_GETGIFTDEPOSIT_MOBILE = 0x00000800;
FLAG_QUICKREG_HANDPHONE =	 0x00000800;    -- 手机发送 

FLAG_ENTERROOM_HANDPHONE =	 0x00000800;      --手机进入 
FLAG_ENTERROOM_EXEBUILDNO =	 0x00004000;      -- 进房间需要检查游戏buildno
FLAG_GETWEBSIGN_HANDPHONE =  0x00000800;      --手机发送 
FLAG_QUERYUSERGAMEINFO_HANDPHONE = 0x00000800;      --手机发送 
FLAG_GETRNDKEY_MOBILE =  	       0x00000800;    --移动端获取

FLAG_CLIENTINFO_ANDPHONE =   0x00000010;  -- 安卓手机
FLAG_CLIENTINFO_IOSPHONE =   0x00000020;  -- 苹果手机
FLAG_CLIENTINFO_IOSPAD =     0x00000040;  -- 苹果平板
FLAG_GETSERVERS_NOTIFY =        0x00000001;  --获取server时用通知形式返回
FLAG_GETROOMS_INCLUDE_ONLINES = 0x00000002;  --获取在线人数
FLAG_REGUSER_QUICK =        0x00000010;  --一键注册
ROOM_OPT_NEEDDEPOSIT =	    0x00000004;
FLAG_SUPPORT_KEEPDEPOSIT =	0x00000001;	--客户端存银子请求如果带上这个标记，表示客户端支持了KEEPDEPOSIT_LIMIT
FLAG_ENTERROOMOK_CLOAKING = 0x00000008;  -- 隐身
FLAG_UPDATE_CLOTHING =		0x00000001;
FLAG_UPDATE_MEMBER =		0x00000002;
USER_TYPE_MEMBER =			0x00000001;	--会员

FLAG_REGUSER_SIMULATOR =	0x00000020;  --从模拟器注册
FLAG_LOGON_SIMULATOR =	    0x00000020;  --从模拟器登录

ROOM_CFG_RANDOM =           0x00000002; --随机
ROOM_CFG_CLOAKING = 		0x00000008; --隐身房
}--target.Flags

target.ext = {
SERVER_TYPE_HALL =	 1;	--大厅服务器
SERVER_TYPE_CHECK =	 2;	--帐户服务器
SERVER_TYPE_DOWN =   3;	--下载服务器 (此定义必须固定值,应对版本升级)
GROUP_TYPE_DEFAULT = 1;
}

function target.key( id )
  return table.keyof(target, id) or id..'.id not find'
end

target.BOOL_FALSE = 0
target.BOOL_TRUE = 1

return target